version: '3'

volumes:

  skypass-pg-data: {}

services:

  totvs-startech-postgres:
    image: postgres:11.5-alpine
    restart: always
    environment:
      POSTGRES_DB: skypass-dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: skypass@123
    ports:
      - 5432:5432
    volumes:
      - skypass-pg-data:/var/lib/postgresql

  totvs-startech-pg-admin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: dev@skypass.com.br
      PGADMIN_DEFAULT_PASSWORD: dev
    ports:
      - 8000:80