server:
  port: 8888

logging:
  level:
    ROOT: INFO
    
spring:
  profiles: dev

  datasource:
    url: jdbc:postgresql://localhost:5432/skypass-dev
    username: postgres
    password: skypass@123

  jpa:
    show-sql: true  
    hibernate:
      format_sql: true
      ddl-auto: update
      show_sql: true
      hbm2ddl:
        auto: "none"